version: '3.9'

services:
  app:
    container_name: liquide-app
    build:
      context: .
      dockerfile: docker-files/Dockerfile-app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/share/app
    networks:
      - app-network
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
  redis:
    container_name: liquide-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
      interval: 5s
    image: redis:7.0.4-alpine
    expose:
      - 6379
    networks:
      - app-network
  mongo:
    container_name: liquide-database
    healthcheck:
      test: ["CMD", "mongo", "--eval", "printjson(db.runCommand({ping: 1}))"]
      retries: 3
      timeout: 5s
      interval: 5s
    image: mongo
    expose:
      - 27017
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=liquide
      - MONGO_INITDB_ROOT_PASSWORD=liquide
      - MONGO_INITDB_DATABASE=liquide

networks:
  app-network:
    external: false
    name: app-network
    driver: bridge